let books = [
  {
    id: "0",
    title: "Les Misérables",
    author: "Victor Hugo",
    price: 14.95,
    category: "Drame",
    releaseDate: new Date("1862,11,22"),
    nbSales: 395,
    nbStock: 198,
    cover: "img/les-miserables.png",
    note: 5,
  },
  {
    id: "1",
    title: "Fight Club",
    author: "Chuck Palahniuk",
    price: 9.99,
    category: "Drame",
    releaseDate: new Date("1996,01,14"),
    nbSales: 365,
    nbStock: 237,
    cover: "img/default.jpeg",
    note: 4,
  },
  {
    id: "2",
    title: "L'étranger",
    author: "Albert Camus",
    price: 14.95,
    category: "Roman",
    releaseDate: new Date("1942,05,29"),
    nbSales: 426,
    nbStock: 156,
    cover: "img/default.jpeg",
    note: 3,
  },
  {
    id: "3",
    title: "Les Fleures du mal",
    author: "Charles Baudelaire",
    price: 19.95,
    category: "Poésie",
    releaseDate: new Date("1857,04,15"),
    nbSales: 598,
    nbStock: 206,
    cover: "img/default.jpeg",
    note: 2,
  },
  {
    id: "4",
    title: "Le petit Prince",
    author: "Antoine de saint-Exupéry",
    price: 7.99,
    category: "Roman",
    releaseDate: new Date("1943,07,15"),
    nbSales: 523,
    nbStock: 68,
    cover: "img/default.jpeg",
    note: 1,
  },
  {
    id: "5",
    title: "Cyrano de Bergerac",
    author: "Edmond Rostand",
    price: 22.5,
    category: "Théâtre",
    releaseDate: new Date("1897,09,20"),
    nbSales: 361,
    nbStock: 0,
    cover: "img/default.jpeg",
    note: 0,
  },
  {
    id: "6",
    title: "Voyage au bout de la nuit",
    author: "Louis-Ferdinand Céline",
    price: 15.7,
    category: "Roman",
    releaseDate: new Date("1932,12,03"),
    nbSales: 371,
    nbStock: 26,
    cover: "img/default.jpeg",
    note: 2,
  },
  {
    id: "7",
    title: "Bel-ami",
    author: "Guy de Maupassant",
    price: 25.0,
    category: "Roman",
    releaseDate: new Date("1885,02,06"),
    nbSales: 230,
    nbStock: 45,
    cover: "img/default.jpeg",
    note: 4,
  },
  {
    id: "8",
    title: "Antigone",
    author: "Jean Anouilh",
    price: 12.7,
    category: "Roman",
    releaseDate: new Date("1944,12,03"),
    nbSales: 171,
    nbStock: 0,
    cover: "img/default.jpeg",
    note: 3,
  },
  {
    id: "9",
    title: "Les Royaumes du Nord",
    author: "Philip Pullman",
    price: 6.5,
    category: "Roman",
    releaseDate: new Date("1995,07,03"),
    nbSales: 1056,
    nbStock: 5489,
    cover: "img/default.jpeg",
    note: 5,
  },
];

